### ISSUE TITLE
Errors setting up

### ISSUE THREAD

**Issue by thesoftwarejedi** [OverloadUT/alexa-plex#20]
So I've got everything configured here, and it looks like it's getting a 404 from the API.

One dotenv setting I'm unclear on is "PLEXPLAYER_NAME".  What should that be?  Could it cause this?  I'm ideally trying to get this to control whats streaming to my chromecast.

START RequestId: 7ea94e2d-30fa-11e5-a88d-83ba84ec1dd3 
2015-07-23T05:20:12.975Z	7ea94e2d-30fa-11e5-a88d-83ba84ec1dd3	Request: { type: 'IntentRequest', requestId: 'amzn1.echo-api.request.8b7d3428-b770-499b-81c0-9110b55f5f65', timestamp: '2015-07-23T05:20:12Z', intent: { name: 'StartShowIntent', slots: { showName: [Object] } } } 
2015-07-23T05:20:12.976Z	7ea94e2d-30fa-11e5-a88d-83ba84ec1dd3	Slots: { showName: { name: 'showName', value: 'arrested development' } } 
2015-07-23T05:20:13.065Z	7ea94e2d-30fa-11e5-a88d-83ba84ec1dd3	Error thrown in promise chain 
2015-07-23T05:20:13.065Z	7ea94e2d-30fa-11e5-a88d-83ba84ec1dd3	Error: Plex Server didnt respond with status code 200, response code: 404 at Request.onResponse [as _callback] (/var/task/node_modules/plex-api/lib/api.js:127:36) at Request.self.callback (/var/task/node_modules/plex-api/node_modules/request/request.js:198:22) at Request.emit (events.js:98:17) at Request.<anonymous> (/var/task/node_modules/plex-api/node_modules/request/request.js:1057:14) at Request.emit (events.js:117:20) at IncomingMessage.<anonymous> (/var/task/node_modules/plex-api/node_modules/request/request.js:1003:12) at IncomingMessage.emit (events.js:117:20) at _stream_readable.js:944:16 at process._tickCallback (node.js:442:13) 
END RequestId: 7ea94e2d-30fa-11e5-a88d-83ba84ec1dd3 
REPORT RequestId: 7ea94e2d-30fa-11e5-a88d-83ba84ec1dd3	Duration: 89.99 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 23 MB

**Comment by OverloadUT** [comment]
Hmmm, this definitely highlights the need for better logging for configuration issues. The StartShow does a lot of Plex API calls to do its thing, and I can't tell which is returning a 404.

Can you try an "On Deck" intent to see if you get a 404 there as well? That'll help narrow down if it's a server request or the client request that's failing.

**Comment by thesoftwarejedi** [comment]
I get this (emphasis mine)

2015-07-23T22:00:24.238Z	3695bdf4-3186-11e5-92ca-2145ab6c0f28	**ERROR from Plex API on Query /library/onDeck**
2015-07-23T22:00:24.239Z	3695bdf4-3186-11e5-92ca-2145ab6c0f28	**[TypeError: Cannot call method 'replace' of undefined]**

**Comment by thesoftwarejedi** [comment]
I'm hunting it down, I added a stack trace output and see where I need to explore...

at buildNaturalLangList (/var/task/index.js:486:25) at /var/task/index.js:81:37 at _fulfilled (/var/task/node_modules/q/q.js:834:54) at self.promiseDispatch.done (/var/task/node_modules/q/q.js:863:30) at Promise.promise.promiseDispatch (/var/task/node_modules/q/q.js:796:13) at /var/task/node_modules/q/q.js:604:44 at runSingle (/var/task/node_modules/q/q.js:137:13) at flush (/var/task/node_modules/q/q.js:125:13) at process._tickCallback (node.js:442:13)

**Comment by OverloadUT** [comment]
Hmmm, oddly enough I think that's exposing a completely different bug that I need to look in to. I think that's an issue with my buildNaturalLangList method.

For the original issue, ```PLEXPLAYER_NAME``` should be the name of the computer running the Plex player you want to control. When you go to http://app.plex.tv/web/app# you should be able to see the name of the player when you click the little "rectangle with wifi" icon in the top right.

Try setting that, and then running the original request for arrested development again. I'm interested if that produces a different result.

**Comment by thesoftwarejedi** [comment]
I submitted a pull req to fix the on deck issue.  That works now - not clear on why the array had empty items but that patch at least avoids it. for now.... :8ball:

**Comment by thesoftwarejedi** [comment]
This could get interesting, the "computer" that's running plex is just my web browser.  Not an instance of home theater...  It's identified by plex under devices as "Plex Web (Chrome)"

![image](https://cloud.githubusercontent.com/assets/6439434/8863893/706b5fec-316a-11e5-8d52-f88cdf7c4715.png)

**Comment by thesoftwarejedi** [comment]
Some toying with the API.  I use my browser as the player and chromecast it to the TV.

/clients **never returns anything :(**

While playing, and only while actively playing, 

Calling **/status/sessions** has some information:

When in browser it's identified as:
<Player machineIdentifier="pcrbxta71cibpgb9_Video" platform="Chrome" product="Plex Web" state="playing" title="Plex Web (Chrome)"/>

When I chromecast the player, it becomes:
<Player machineIdentifier="l0al0np11ao47vi_Video" platform="Chromecast" product="Plex Chromecast" state="playing" title="Chromecast"/>


I may have to do a lot of tweaking to get this to work.

**Comment by OverloadUT** [comment]
Ah ha!

The issue here might be that Plex Web does not register itself as a device that can be controlled via the API (which is why it never shows up in /clients). If that's the case, there's no "official" way to remotely control that player :( (this is likely because the web app running in your browser cannot respond to any network requests directly, as that's outside the scope of what a webpage can do)

Might be able to hack something in even moreso than the current reverse-engineered API is, but as you said it'll require some digging

**Comment by thesoftwarejedi** [comment]
OK, so I'm troubleshooting it through my home theater machine.  Still having the same problem but can do the digging around myself.  I'll report back if this is an issue still.
